# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import battlecity_pb2 as proto_dot_battlecity__pb2


class battlecityServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AckOp = channel.unary_unary(
                '/battlecity.battlecityService/AckOp',
                request_serializer=proto_dot_battlecity__pb2.AckRequest.SerializeToString,
                response_deserializer=proto_dot_battlecity__pb2.AckReply.FromString,
                )
        self.GetOp = channel.unary_unary(
                '/battlecity.battlecityService/GetOp',
                request_serializer=proto_dot_battlecity__pb2.OpRequest.SerializeToString,
                response_deserializer=proto_dot_battlecity__pb2.AckReply.FromString,
                )
        self.GetMap = channel.unary_unary(
                '/battlecity.battlecityService/GetMap',
                request_serializer=proto_dot_battlecity__pb2.AckRequest.SerializeToString,
                response_deserializer=proto_dot_battlecity__pb2.MapReply.FromString,
                )
        self.SendTank = channel.unary_unary(
                '/battlecity.battlecityService/SendTank',
                request_serializer=proto_dot_battlecity__pb2.TankRequest.SerializeToString,
                response_deserializer=proto_dot_battlecity__pb2.AckReply.FromString,
                )


class battlecityServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def AckOp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetOp(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMap(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SendTank(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_battlecityServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AckOp': grpc.unary_unary_rpc_method_handler(
                    servicer.AckOp,
                    request_deserializer=proto_dot_battlecity__pb2.AckRequest.FromString,
                    response_serializer=proto_dot_battlecity__pb2.AckReply.SerializeToString,
            ),
            'GetOp': grpc.unary_unary_rpc_method_handler(
                    servicer.GetOp,
                    request_deserializer=proto_dot_battlecity__pb2.OpRequest.FromString,
                    response_serializer=proto_dot_battlecity__pb2.AckReply.SerializeToString,
            ),
            'GetMap': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMap,
                    request_deserializer=proto_dot_battlecity__pb2.AckRequest.FromString,
                    response_serializer=proto_dot_battlecity__pb2.MapReply.SerializeToString,
            ),
            'SendTank': grpc.unary_unary_rpc_method_handler(
                    servicer.SendTank,
                    request_deserializer=proto_dot_battlecity__pb2.TankRequest.FromString,
                    response_serializer=proto_dot_battlecity__pb2.AckReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'battlecity.battlecityService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class battlecityService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def AckOp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/battlecity.battlecityService/AckOp',
            proto_dot_battlecity__pb2.AckRequest.SerializeToString,
            proto_dot_battlecity__pb2.AckReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetOp(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/battlecity.battlecityService/GetOp',
            proto_dot_battlecity__pb2.OpRequest.SerializeToString,
            proto_dot_battlecity__pb2.AckReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMap(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/battlecity.battlecityService/GetMap',
            proto_dot_battlecity__pb2.AckRequest.SerializeToString,
            proto_dot_battlecity__pb2.MapReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SendTank(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/battlecity.battlecityService/SendTank',
            proto_dot_battlecity__pb2.TankRequest.SerializeToString,
            proto_dot_battlecity__pb2.AckReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
